/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
   
  GetStarted:[
   {
      type: 'doc',
      id: 'overview',
      label: "Overview"
    },
	{
      type: 'doc',
      id: 'get-started',
      label: "Getting Started"
    },
  ],
  Guides:[
   {
      type: 'category',
      label: 'Concepts',
	  link: {
			type: 'generated-index',
			title: 'Concepts',
			description: 'Description of the main concepts implemented in Qodly.',
			slug: '/category/concepts',
			keywords: ['concepts'],
			image: '/img/docusaurus.png',
			},
      items: ['concepts/server-architecture','concepts/db'],
    },
  ],
  QodlyScript:[
   		{ 	type: 'category',
			label: 'QodlyScript overview',
			link: {
				type: 'generated-index',
				title: 'QodlyScript overview',
				description: 'Main concepts of the QodlyScript Language.',
				slug: '/category/language',
				keywords: ['language'],
				image: '/img/docusaurus.png',
			},
			items: ['concepts/lang-quicktour',
				'concepts/lang-variables',
				'concepts/lang-arrays',
				{ 	type: 'category',
					label: 'Data Types',
					link: {
						type: 'doc',
						id: 'concepts/lang-data-types',
					},
					items: [
						'concepts/lang-blob',
						'concepts/lang-boolean',
						'concepts/lang-date',
						'concepts/lang-number',
						'concepts/lang-picture',
						'concepts/lang-text',
					],
				},
				'concepts/lang-operators',
				'concepts/lang-methods',
				'concepts/lang-parameters',
				'concepts/lang-shared',
				'concepts/lang-classes',
				'concepts/lang-control-flow',
				'concepts/lang-errors',
				'concepts/lang-identifiers',
				'concepts/lang-pathnames',
				],
		},
 {
      type: 'doc',
      id: 'language/string',
      label: "String"
    },
  ],
};

module.exports = sidebars;
